name: Renovate

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes; adjust if you prefer less frequent
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          config-file: .github/renovate.json
