name: Renovate
on:
  schedule:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug repo & config presence
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          git remote -v
          ls -R .github | head -100
          cat .github/renovate.json || echo "renovate.json not found"
      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: ${{ github.repository }}
