name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: renovate-${{ github.repository }}
  cancel-in-progress: false

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: Debug repo & config presence
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          git remote -v
          ls -R .github | head -100 || true
          cat .github/renovate.json || echo "renovate.json not found"

      - name: Run Renovate (with PAT)
        uses: renovatebot/github-action@v43.0.11
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: 41.97.4   # pin to a known Renovate CLI version
          # configurationFile: .github/renovate.json # optional if config is here
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: ${{ github.repository }}
